"""initial

Revision ID: b7c5001a8d10
Revises: 
Create Date: 2019-01-22 01:52:49.696895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7c5001a8d10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('icon', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_types_name'), 'device_types', ['name'], unique=True)
    op.create_table('lesson_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('color', sa.Unicode(length=64), nullable=True),
    sa.Column('view_point', sa.Unicode(length=64), nullable=True),
    sa.Column('login_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_types_name'), 'lesson_types', ['name'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('category', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_category'), 'permissions', ['category'], unique=False)
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('category', sa.Unicode(length=64), nullable=True),
    sa.Column('icon', sa.Unicode(length=64), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_category'), 'roles', ['category'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_name'), 'rooms', ['name'], unique=True)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('abbr', sa.Unicode(length=64), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('progress_threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['lesson_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_name'), 'lessons', ['name'], unique=True)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_mac', sa.Unicode(length=64), nullable=True),
    sa.Column('suspended', sa.Boolean(), nullable=True),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('name_pinyin', sa.Unicode(length=64), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_name_pinyin'), 'users', ['name_pinyin'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.Unicode(length=64), nullable=True),
    sa.Column('alias', sa.Unicode(length=64), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('mac_address', sa.Unicode(length=64), nullable=True),
    sa.Column('category', sa.Unicode(length=64), nullable=True),
    sa.Column('obsolete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['device_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_category'), 'devices', ['category'], unique=False)
    op.create_index(op.f('ix_devices_serial'), 'devices', ['serial'], unique=True)
    op.create_table('user_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.UnicodeText(), nullable=True),
    sa.Column('category', sa.Unicode(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_logs_category'), 'user_logs', ['category'], unique=False)
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=64), nullable=True),
    sa.Column('abbr', sa.Unicode(length=64), nullable=True),
    sa.Column('description', sa.Unicode(length=64), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Interval(), nullable=True),
    sa.Column('file_name', sa.Unicode(length=64), nullable=True),
    sa.Column('hls_cache_file_name', sa.Unicode(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_name'), 'videos', ['name'], unique=False)
    op.create_table('device_lesson_types',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('lesson_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['lesson_type_id'], ['lesson_types.id'], ),
    sa.PrimaryKeyConstraint('device_id', 'lesson_type_id')
    )
    op.create_table('punches',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('play_time', sa.Interval(), nullable=True),
    sa.Column('synchronized', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'video_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('punches')
    op.drop_table('device_lesson_types')
    op.drop_index(op.f('ix_videos_name'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_user_logs_category'), table_name='user_logs')
    op.drop_table('user_logs')
    op.drop_index(op.f('ix_devices_serial'), table_name='devices')
    op.drop_index(op.f('ix_devices_category'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_name_pinyin'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_lessons_name'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_rooms_name'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_category'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_category'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_lesson_types_name'), table_name='lesson_types')
    op.drop_table('lesson_types')
    op.drop_index(op.f('ix_device_types_name'), table_name='device_types')
    op.drop_table('device_types')
    # ### end Alembic commands ###
